/*
 * Copyright 2026 dorkbox, llc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package dorkbox.gradlePublish.portal.impl.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param sortField The field to sort the results by.
 * @param page The page number.
 * @param propertySize The number of items per page.
 * @param sortDirection The direction of the sorting (asc or desc).
 * @param deploymentIds Optional deployment IDs.
 * @param pathStarting Optional starting path.
 */
@Serializable

data class ApiV1PublisherDeploymentsFilesPostRequest (

    /* The field to sort the results by. */
    @SerialName(value = "sortField") @Required val sortField: String,

    /* The page number. */
    @SerialName(value = "page") val page: Double? = null,

    /* The number of items per page. */
    @SerialName(value = "size") val propertySize: Double? = null,

    /* The direction of the sorting (asc or desc). */
    @SerialName(value = "sortDirection") val sortDirection: String? = null,

    /* Optional deployment IDs. */
    @SerialName(value = "deploymentIds") val deploymentIds: List<String>? = null,

    /* Optional starting path. */
    @SerialName(value = "pathStarting") val pathStarting: String? = null
)

