/*
 * Copyright 2026 dorkbox, llc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package dorkbox.gradlePublish.portal.impl.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 
 *
 * @param relativePath 
 * @param fileName 
 * @param fileSize 
 * @param fileTimestamp 
 */
@Serializable

data class DeployedFileDTO (
    @SerialName(value = "relativePath") val relativePath: String? = null,
    @SerialName(value = "fileName") val fileName: String? = null,
    @SerialName(value = "fileSize") val fileSize: Double? = null,
    @SerialName(value = "fileTimestamp") val fileTimestamp: Double? = null
)
