/*
 * Copyright 2026 dorkbox, llc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */


package dorkbox.gradlePublish.portal.impl.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param deploymentId
 * @param deploymentName 
 * @param deploymentState 
 * @param deploymentType 
 * @param createTimestamp 
 * @param purls 
 * @param errors 
 * @param deployedComponentVersions 
 */
@Serializable
data class DeploymentResponseFiles (
    @SerialName(value = "deploymentId") val deploymentId: String? = null,
    @SerialName(value = "deploymentName") val deploymentName: String? = null,
    @SerialName(value = "deploymentState") val deploymentState: DeploymentState? = null,
    @SerialName(value = "deploymentType") val deploymentType: DeploymentType? = null,
    @SerialName(value = "createTimestamp") val createTimestamp: Double? = null,
    @SerialName(value = "purls") val purls: List<String>? = null,
    @SerialName(value = "errors") val errors: DeploymentResponseFilesErrors? = null,
    @SerialName(value = "deployedComponentVersions") val deployedComponentVersions: List<DeployedComponentVersion>? = null
) {

    /**
     * Values: PENDING,VALIDATING,VALIDATED,PUBLISHING,PUBLISHED,FAILED
     */
    @Serializable
    enum class DeploymentState(val value: String) {
        @SerialName(value = "PENDING") PENDING("PENDING"),
        @SerialName(value = "VALIDATING") VALIDATING("VALIDATING"),
        @SerialName(value = "VALIDATED") VALIDATED("VALIDATED"),
        @SerialName(value = "PUBLISHING") PUBLISHING("PUBLISHING"),
        @SerialName(value = "PUBLISHED") PUBLISHED("PUBLISHED"),
        @SerialName(value = "FAILED") FAILED("FAILED");
    }

    /**
     * Values: BUNDLE,SINGLE
     */
    @Serializable
    enum class DeploymentType(val value: String) {
        @SerialName(value = "BUNDLE") BUNDLE("BUNDLE"),
        @SerialName(value = "SINGLE") SINGLE("SINGLE");
    }
}

