/*
 * Copyright 2026 dorkbox, llc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

package dorkbox.gradlePublish.portal.impl.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * @param name
 * @param path 
 * @param errors 
 */
@Serializable
data class DeployedComponentVersion (
    @SerialName(value = "name") val name: String? = null,
    @SerialName(value = "path") val path: String? = null,
    @SerialName(value = "errors") val errors: List<String>? = null
)
